# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

default:
    suites:
        api_managing_product_associations:
            contexts:
                - sylius.behat.context.hook.doctrine_orm

                - sylius.behat.context.transform.locale
                - sylius.behat.context.transform.product
                - sylius.behat.context.transform.product_association
                - sylius.behat.context.transform.product_association_type
                - sylius.behat.context.transform.shared_storage

                - sylius.behat.context.setup.admin_api_security
                - sylius.behat.context.setup.channel
                - sylius.behat.context.setup.locale
                - sylius.behat.context.setup.product
                - sylius.behat.context.setup.product_association

                - sylius.behat.context.api.admin.managing_product_associations

            filters:
                tags: "@managing_product_associations && @api"
            javascript: false
